import { SectionType } from "./types.js";

export interface PatternConfig {
  name: string;
  regex: RegExp;
}

export const CPINFO_PATTERNS: PatternConfig[] = [
  { name: "main_section", regex: new RegExp("^={46}\\s*\\n([^\\n=]+?)\\s*\\n={46}", "gm") },
  { name: "file_section", regex: new RegExp("^-{66}\\s*\\n([^\\n]+?)\\s*\\n-{66}", "gm") },
  { name: "sub_section_short", regex: new RegExp("^-{24}\\s*\\n([^\\n]+?)\\s*\\n-{24}", "gm") },
  { name: "sub_section_medium", regex: new RegExp("^-{23}\\s*\\n([^\\n]+?)\\s*\\n-{23}", "gm") }
];

export const PATTERN_PRIORITY: Record<string, number> = {
  main_section: 1,
  file_section: 2,
  sub_section_short: 3,
  sub_section_medium: 3
};

export const SECTION_TYPE_MAPPING: { pattern: string; type: SectionType }[] = [
  { pattern: "enterprise system overview", type: SectionType.SYSTEM_INFO },
  { pattern: "global system configuration", type: SectionType.SYSTEM_INFO },
  { pattern: "system info", type: SectionType.SYSTEM_INFO },
  { pattern: "general info", type: SectionType.SYSTEM_INFO },
  { pattern: "cp components", type: SectionType.MONITORING },
  { pattern: "cp status", type: SectionType.MONITORING },
  { pattern: "cpstat", type: SectionType.MONITORING },
  { pattern: "identityserver", type: SectionType.MONITORING },
  { pattern: "antimalware", type: SectionType.MONITORING },
  { pattern: "threat-emulation", type: SectionType.MONITORING },
  { pattern: "https_inspection", type: SectionType.MONITORING },
  { pattern: "ips status", type: SectionType.MONITORING },
  { pattern: "product keys", type: SectionType.MONITORING },
  { pattern: "hostid", type: SectionType.MONITORING },
  { pattern: "uname -a", type: SectionType.SYSTEM_INFO },
  { pattern: "os data", type: SectionType.SYSTEM_INFO },
  { pattern: "version", type: SectionType.SYSTEM_INFO },
  { pattern: "hostname", type: SectionType.SYSTEM_INFO },
  { pattern: "platform", type: SectionType.SYSTEM_INFO },
  { pattern: "hardware", type: SectionType.SYSTEM_INFO },
  { pattern: "operating system", type: SectionType.SYSTEM_INFO },
  { pattern: "df -", type: SectionType.SYSTEM_INFO },
  { pattern: "du -sh", type: SectionType.SYSTEM_INFO },
  { pattern: "mount listing", type: SectionType.SYSTEM_INFO },
  { pattern: "package manager report", type: SectionType.SYSTEM_INFO },
  { pattern: "smartctl", type: SectionType.SYSTEM_INFO },
  { pattern: "network infrastructure", type: SectionType.NETWORK },
  { pattern: "network", type: SectionType.NETWORK },
  { pattern: "interface", type: SectionType.NETWORK },
  { pattern: "routing", type: SectionType.NETWORK },
  { pattern: "bond", type: SectionType.NETWORK },
  { pattern: "bridge", type: SectionType.NETWORK },
  { pattern: "vlan", type: SectionType.NETWORK },
  { pattern: "ethernet", type: SectionType.NETWORK },
  { pattern: "vpn", type: SectionType.VPN },
  { pattern: "ipsec", type: SectionType.VPN },
  { pattern: "tunnel", type: SectionType.VPN },
  { pattern: "site-to-site", type: SectionType.VPN },
  { pattern: "remote access", type: SectionType.VPN },
  { pattern: "mobile access", type: SectionType.VPN },
  { pattern: "ssl vpn", type: SectionType.VPN },
  { pattern: "encryption domain", type: SectionType.VPN },
  { pattern: "firewall", type: SectionType.FIREWALL },
  { pattern: "rule base", type: SectionType.FIREWALL },
  { pattern: "policy", type: SectionType.FIREWALL },
  { pattern: "access control", type: SectionType.FIREWALL },
  { pattern: "nat", type: SectionType.FIREWALL },
  { pattern: "rules", type: SectionType.FIREWALL },
  { pattern: "connection", type: SectionType.FIREWALL },
  { pattern: "fw1", type: SectionType.FIREWALL },
  { pattern: "virtual systems", type: SectionType.CONFIGURATION },
  { pattern: "blade configuration", type: SectionType.CONFIGURATION },
  { pattern: "security configuration", type: SectionType.SECURITY },
  { pattern: "config", type: SectionType.CONFIGURATION },
  { pattern: "settings", type: SectionType.CONFIGURATION },
  { pattern: "system performance monitoring", type: SectionType.PERFORMANCE },
  { pattern: "performance", type: SectionType.PERFORMANCE },
  { pattern: "cpu", type: SectionType.PERFORMANCE },
  { pattern: "memory", type: SectionType.PERFORMANCE },
  { pattern: "storage", type: SectionType.PERFORMANCE },
  { pattern: "disk", type: SectionType.PERFORMANCE },
  { pattern: "load", type: SectionType.PERFORMANCE },
  { pattern: "utilization", type: SectionType.PERFORMANCE },
  { pattern: "monitoring", type: SectionType.MONITORING },
  { pattern: "alert", type: SectionType.MONITORING },
  { pattern: "threshold", type: SectionType.MONITORING },
  { pattern: "snmp", type: SectionType.MONITORING },
  { pattern: "syslog", type: SectionType.MONITORING },
  { pattern: "notification", type: SectionType.MONITORING },
  { pattern: "process", type: SectionType.PROCESSES },
  { pattern: "daemon", type: SectionType.PROCESSES },
  { pattern: "service", type: SectionType.PROCESSES },
  { pattern: "pid", type: SectionType.PROCESSES },
  { pattern: "task", type: SectionType.PROCESSES },
  { pattern: "ps aux", type: SectionType.PROCESSES },
  { pattern: "ps axf", type: SectionType.PROCESSES },
  { pattern: "ps auxww", type: SectionType.PROCESSES },
  { pattern: "lsof", type: SectionType.PROCESSES },
  { pattern: "logged-in users", type: SectionType.PROCESSES },
  { pattern: "env -", type: SectionType.PROCESSES },
  { pattern: "usr/bin/ps", type: SectionType.PROCESSES },
  { pattern: "database", type: SectionType.DATABASE },
  { pattern: "sql", type: SectionType.DATABASE },
  { pattern: "db", type: SectionType.DATABASE },
  { pattern: "table", type: SectionType.DATABASE },
  { pattern: "schema", type: SectionType.DATABASE },
  { pattern: "log analysis", type: SectionType.LOG_FILES },
  { pattern: "comprehensive log analysis", type: SectionType.LOG_FILES },
  { pattern: "/var/log", type: SectionType.LOG_FILES },
  { pattern: "/opt/cp", type: SectionType.LOG_FILES },
  { pattern: "messages", type: SectionType.LOG_FILES },
  { pattern: "syslog", type: SectionType.LOG_FILES },
  { pattern: "compliance", type: SectionType.SECURITY },
  { pattern: "audit", type: SectionType.SECURITY },
  { pattern: "threat intelligence", type: SectionType.SECURITY },
  { pattern: "user", type: SectionType.SECURITY },
  { pattern: "authentication", type: SectionType.SECURITY },
  { pattern: "authorization", type: SectionType.SECURITY },
  { pattern: "certificate", type: SectionType.SECURITY },
  { pattern: "cphaprob", type: SectionType.FIREWALL },
  { pattern: "syncstat", type: SectionType.FIREWALL },
  { pattern: "ldstat", type: SectionType.FIREWALL },
  { pattern: "fcustat", type: SectionType.FIREWALL },
  { pattern: "show_failover", type: SectionType.FIREWALL },
  { pattern: "ccp", type: SectionType.FIREWALL },
  { pattern: "high availability", type: SectionType.FIREWALL },
  { pattern: "dlpcmd", type: SectionType.FIREWALL },
  { pattern: "floodgate", type: SectionType.FIREWALL },
  { pattern: "cpmonitor", type: SectionType.CONFIGURATION },
  { pattern: "vsx", type: SectionType.CONFIGURATION },
  { pattern: "virtual system", type: SectionType.CONFIGURATION },
  { pattern: "vrfs", type: SectionType.CONFIGURATION },
  { pattern: "ctx", type: SectionType.CONFIGURATION },
  { pattern: "directory listing", type: SectionType.CONFIGURATION },
  { pattern: "file attributes", type: SectionType.CONFIGURATION },
  { pattern: "checksum report", type: SectionType.FIREWALL },
  { pattern: "modules", type: SectionType.FIREWALL },
  { pattern: "java parameters", type: SectionType.CONFIGURATION },
  { pattern: "compatibility pkgs", type: SectionType.CONFIGURATION },
  { pattern: "azure connectivity", type: SectionType.NETWORK },
  { pattern: "risk docker image", type: SectionType.MONITORING },
  { pattern: "risk docker container", type: SectionType.MONITORING },
  { pattern: "cpview - skyline", type: SectionType.MONITORING },
  { pattern: "cpshared", type: SectionType.SYSTEM_INFO },
  { pattern: "provider-1", type: SectionType.CONFIGURATION },
  { pattern: "date", type: SectionType.MONITORING },
  { pattern: "softnet status", type: SectionType.PERFORMANCE },
  { pattern: "fw ctl multik stat", type: SectionType.FIREWALL },
  { pattern: "fw affinity", type: SectionType.FIREWALL },
  { pattern: "fw-1 accelerator", type: SectionType.FIREWALL },
  { pattern: "sim affinity", type: SectionType.FIREWALL },
  { pattern: "kiss kernel", type: SectionType.FIREWALL },
  { pattern: "aesni support", type: SectionType.FIREWALL },
  { pattern: "failopen status", type: SectionType.FIREWALL },
  { pattern: "ipsctl -a", type: SectionType.FIREWALL },
  { pattern: "vs 0", type: SectionType.FIREWALL },
  { pattern: "vs 1", type: SectionType.FIREWALL },
  { pattern: "vs 2", type: SectionType.FIREWALL },
  { pattern: "vs 3", type: SectionType.FIREWALL },
  { pattern: "affinity of multi-queue", type: SectionType.FIREWALL },
  { pattern: "number of active rx queues", type: SectionType.FIREWALL },
  { pattern: "sxlmode -s", type: SectionType.FIREWALL },
  { pattern: "pdp m groups", type: SectionType.SECURITY },
  { pattern: "list pci devices", type: SectionType.PERFORMANCE },
  { pattern: "lspci -v", type: SectionType.PERFORMANCE },
  { pattern: "lspci -vv", type: SectionType.PERFORMANCE },
  { pattern: "lspci -nv", type: SectionType.PERFORMANCE },
  { pattern: "lspci", type: SectionType.PERFORMANCE },
  { pattern: "brctl show", type: SectionType.NETWORK },
  { pattern: "vrf all ifaces", type: SectionType.CONFIGURATION },
  { pattern: "cpwd", type: SectionType.MONITORING },
  { pattern: "uptime", type: SectionType.MONITORING },
  { pattern: "fw ", type: SectionType.FIREWALL },
  { pattern: "env", type: SectionType.PROCESSES },
  { pattern: "final system summary", type: SectionType.SYSTEM_INFO }
];

export const SPECIAL_SECTION_OVERRIDES: Array<{ regex: RegExp; type: SectionType }> = [
  { regex: /^\/etc\/resolv\.conf$/i, type: SectionType.NETWORK },
  { regex: /^\/etc\/hosts$/i, type: SectionType.NETWORK },
  { regex: /^\/etc\/routed\d?\.conf$/i, type: SectionType.NETWORK },
  { regex: /^\/etc\/ppp\//i, type: SectionType.NETWORK },
  { regex: /^\/web\/conf\/httpd2\.conf$/i, type: SectionType.VPN },
  { regex: /^\/web\/conf\/extra\/httpd-ssl\.conf$/i, type: SectionType.VPN },
  { regex: /^\/opt\/postfix\/etc\/postfix\/master\.cf$/i, type: SectionType.DIAGNOSTICS },
  { regex: /^\/opt\/postfix\/etc\/postfix\/main\.cf$/i, type: SectionType.DIAGNOSTICS },
  { regex: /^\/etc\/asset\.xml$/i, type: SectionType.SECURITY },
  { regex: /^\/etc\/features\.xml$/i, type: SectionType.SECURITY },
  { regex: /^\/etc\/hidden_group_names$/i, type: SectionType.SECURITY },
  { regex: /^\/etc\/fw\.boot\/ha_boot\.conf$/i, type: SectionType.FIREWALL },
  { regex: /^\/etc\/ppk\.boot\/bin\/sxlmode\s+-s$/i, type: SectionType.FIREWALL },
  { regex: /^\/usr\/bin\/sshd_template_xlate$/i, type: SectionType.SECURITY },
  { regex: /^\/bin\/dmesg$/i, type: SectionType.DIAGNOSTICS },
  { regex: /^\/etc\/modprobe\.conf$/i, type: SectionType.CONFIGURATION }
];

export const EXTENSION_TYPE_MAPPING: Array<{ regex: RegExp; type: SectionType }> = [
  { regex: /\.elg(\b|$)/, type: SectionType.LOG_FILES },
  { regex: /\.log(\b|$)/, type: SectionType.LOG_FILES },
  { regex: /\.conf(\b|$)/, type: SectionType.CONFIGURATION },
  { regex: /\.cf(\b|$)/, type: SectionType.CONFIGURATION },
  { regex: /\.xml(\b|$)/, type: SectionType.CONFIGURATION },
  { regex: /\.rec(\b|$)/, type: SectionType.CONFIGURATION }
];

export const KEYWORD_PATTERNS: Record<SectionType, string[]> = {
  [SectionType.PERFORMANCE]: [
    "cpu",
    "memory",
    "performance",
    "monitoring",
    "storage",
    "load",
    "utilization",
    "disk",
    "smartctl",
    "accelerator",
    "multi-queue",
    "lspci"
  ],
  [SectionType.NETWORK]: [
    "network",
    "interface",
    "routing",
    "bond",
    "bridge",
    "vlan",
    "ethernet",
    "ip route",
    "ip -6 route",
    "ip link",
    "ip addr",
    "ip rule",
    "ip maddr",
    "ip mroute",
    "ip neighbor",
    "netstat",
    "arp -an",
    "softnet",
    "fw ctl iflist",
    "fw getifs",
    "fw ctl multik",
    "fw affinity",
    "/proc/net/",
    "snmp6",
    "tcp6",
    "udp6",
    "fib_trie",
    "igmp",
    "if_inet6",
    "azure connectivity",
    "anycast6",
    "curl_cli",
    "nslookup"
  ],
  [SectionType.VPN]: ["vpn", "ipsec", "tunnel", "site-to-site", "remote access", "ssl vpn"],
  [SectionType.FIREWALL]: ["firewall", "rule base", "policy", "access control", "nat", "rules", "fw1"],
  [SectionType.SECURITY]: [
    "security",
    "compliance",
    "audit",
    "threat",
    "user",
    "auth",
    "certificate",
    "pdp m groups",
    "sshd_template_xlate"
  ],
  [SectionType.PROCESSES]: [
    "process",
    "daemon",
    "service",
    "pid",
    "task",
    "ps ",
    "lsof",
    "w -u",
    "environment",
    "grep sdwan",
    "grep cp-nano",
    "usr/bin/ps"
  ],
  [SectionType.DATABASE]: ["database", "sql", "db", "table", "schema"],
  [SectionType.MONITORING]: [
    "monitoring",
    "alert",
    "threshold",
    "snmp",
    "notification",
    "vmstat",
    "top -b",
    "sar",
    "cpstat",
    "cpview",
    "/proc/stat",
    "risk docker",
    "cp components",
    "cp status",
    "uptime",
    "date"
  ],
  [SectionType.LOG_FILES]: ["log", "audit", "messages", "var/log", "syslog", ".elg"],
  [SectionType.SYSTEM_INFO]: [
    "system",
    "info",
    "general",
    "version",
    "overview",
    "summary",
    "hostname",
    "platform",
    "hardware",
    "lsdev",
    "sysenv",
    "smt status",
    "os assets",
    "rpm",
    "smartctl",
    "df -",
    "du -sh",
    "mount listing",
    "lsiutil"
  ],
  [SectionType.CORE_DUMPS]: ["core", "dump", "crash", "segfault", "abort"],
  [SectionType.LICENSING]: ["licensing", "license", "entitlement", "blade", "contract"],
  [SectionType.COMMAND_OUTPUT]: ["command", "output", "result", "execute", "run"],
  [SectionType.DIAGNOSTICS]: [
    "diagnostic",
    "debug",
    "trace",
    "error",
    "warning",
    "dmesg",
    "postfix",
    "pdmesg"
  ],
  [SectionType.CONFIGURATION]: [
    "config",
    "policy",
    "settings",
    "blade",
    "virtual",
    "/etc/",
    "/conf/",
    "directory listing",
    "java parameters",
    "compatibility pkgs",
    "snmpd.conf"
  ],
  [SectionType.UNKNOWN]: []
};

