// Auto-generated Zod schemas from JSON schemas
// Generated on: 2026-03-08T12:22:58.075Z

import { z } from 'zod';

export const zodSchemas = {
  ShowCardInfo: { domain: z.string().optional(), domains_to_process: z.enum(["ALL_DOMAINS_ON_THIS_SERVER", "CURRENT_DOMAIN"]).optional() },
  ShowConfig: { domain: z.string().optional(), domains_to_process: z.enum(["ALL_DOMAINS_ON_THIS_SERVER", "CURRENT_DOMAIN"]).optional() },
  ShowRulesUidsWithSuggestions: { domain: z.string().optional(), domains_to_process: z.enum(["ALL_DOMAINS_ON_THIS_SERVER", "CURRENT_DOMAIN"]).optional(), "requestBody": z.object({ "layer": z.string().uuid().regex(new RegExp("^[0-9a-fA-F]{8}(?:-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}$")).describe("Access layer identifier in UUID format"), "filters": z.object({ "states": z.array(z.enum(["ACCEPTED","REJECTED"]).describe("State of a suggestion - either ACCEPTED or REJECTED")).describe("Array of insight state values").optional(), "user-interaction": z.object({ "operator": z.enum(["NOT-IN","IN"]).describe("Operator for filtering by user-interaction-types").optional(), "types": z.array(z.literal("DECIDE_LATER").describe("Type of user interaction with an insight")).describe("Array of user interaction type values") }).optional(), "security-impact": z.enum(["HIGH","MEDIUM_AND_ABOVE","LOW_AND_ABOVE"]).describe("Minimum security impact threshold to include").optional(), "confidence-level": z.enum(["HIGH","MEDIUM_AND_ABOVE","LOW_AND_ABOVE"]).describe("Minimum confidence threshold to include").optional(), "default-filter": z.literal("NONE").describe("Ignore default filtering of the system").optional(), "suggestions-type": z.enum(["unused-objects","tighten-rule","delete-disabled-rule","zero-hits-rule"]).describe("Type of insight") }) }).describe("Parameters for showing rules UIDs with their suggestions") },
  ShowState: { domain: z.string().optional(), domains_to_process: z.enum(["ALL_DOMAINS_ON_THIS_SERVER", "CURRENT_DOMAIN"]).optional() },
  ShowSuggestionEngineMetadata: { domain: z.string().optional(), domains_to_process: z.enum(["ALL_DOMAINS_ON_THIS_SERVER", "CURRENT_DOMAIN"]).optional(), "requestBody": z.object({ "filters": z.object({ "suggestion-type": z.enum(["unused-objects","tighten-rule","delete-disabled-rule","zero-hits-rule"]).describe("Type of insight").optional() }).optional() }).describe("The JSON request body.") },
  ShowSuggestions: { domain: z.string().optional(), domains_to_process: z.enum(["ALL_DOMAINS_ON_THIS_SERVER", "CURRENT_DOMAIN"]).optional(), "requestBody": z.object({ "layer": z.string().uuid().regex(new RegExp("^[0-9a-fA-F]{8}(?:-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}$")).describe("Access layer identifier in UUID format").optional(), "options": z.object({ "include-inline-layers": z.boolean().describe("Whether to include insights on inline layers").optional() }).optional(), "limit": z.number().describe("Maximum number of items to return").optional(), "offset": z.number().describe("Number of items to skip for pagination").optional(), "filters": z.object({ "states": z.array(z.enum(["ACCEPTED","REJECTED"]).describe("State of a suggestion - either ACCEPTED or REJECTED")).describe("Array of insight state values").optional(), "user-interaction": z.object({ "operator": z.enum(["NOT-IN","IN"]).describe("Operator for filtering by user-interaction-types").optional(), "types": z.array(z.literal("DECIDE_LATER").describe("Type of user interaction with an insight")).describe("Array of user interaction type values") }).optional(), "security-impact": z.enum(["HIGH","MEDIUM_AND_ABOVE","LOW_AND_ABOVE"]).describe("Minimum security impact threshold to include").optional(), "confidence-level": z.enum(["HIGH","MEDIUM_AND_ABOVE","LOW_AND_ABOVE"]).describe("Minimum confidence threshold to include").optional(), "default-filter": z.literal("NONE").describe("Ignore default filtering of the system").optional(), "uids": z.array(z.string().uuid().regex(new RegExp("^[0-9a-fA-F]{8}(?:-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}$")).describe("Stringified UUID.")).describe("Array of insight unique identifiers").optional(), "rules-uids": z.array(z.string().uuid().regex(new RegExp("^[0-9a-fA-F]{8}(?:-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}$")).describe("Stringified UUID.")).describe("Array of rule unique identifiers").optional(), "types": z.array(z.enum(["unused-objects","tighten-rule","delete-disabled-rule","zero-hits-rule"]).describe("Type of insight")).describe("Type of insight").optional() }).optional() }).describe("Parameters for showing suggestions with enhanced v3.0 capabilities") },
  ShowSuggestionsInfo: { domain: z.string().optional(), domains_to_process: z.enum(["ALL_DOMAINS_ON_THIS_SERVER", "CURRENT_DOMAIN"]).optional(), "requestBody": z.object({ "layer": z.string().uuid().regex(new RegExp("^[0-9a-fA-F]{8}(?:-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}$")).describe("Access layer identifier in UUID format") }).describe("The JSON request body.") },
  ShowSuggestionsSummary: { domain: z.string().optional(), domains_to_process: z.enum(["ALL_DOMAINS_ON_THIS_SERVER", "CURRENT_DOMAIN"]).optional(), "requestBody": z.object({ "layer": z.string().uuid().regex(new RegExp("^[0-9a-fA-F]{8}(?:-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}$")).describe("Access layer identifier in UUID format").optional(), "filters": z.object({ "states": z.array(z.enum(["ACCEPTED","REJECTED"]).describe("State of a suggestion - either ACCEPTED or REJECTED")).describe("Array of insight state values").optional(), "user-interaction": z.object({ "operator": z.enum(["NOT-IN","IN"]).describe("Operator for filtering by user-interaction-types").optional(), "types": z.array(z.literal("DECIDE_LATER").describe("Type of user interaction with an insight")).describe("Array of user interaction type values") }).optional(), "security-impact": z.enum(["HIGH","MEDIUM_AND_ABOVE","LOW_AND_ABOVE"]).describe("Minimum security impact threshold to include").optional(), "confidence-level": z.enum(["HIGH","MEDIUM_AND_ABOVE","LOW_AND_ABOVE"]).describe("Minimum confidence threshold to include").optional(), "default-filter": z.literal("NONE").describe("Ignore default filtering of the system").optional() }).optional() }).describe("Parameters for showing suggestions summary") },
  ShowPolicyInsightsStatus: { domain: z.string().optional(), domains_to_process: z.enum(["ALL_DOMAINS_ON_THIS_SERVER", "CURRENT_DOMAIN"]).optional() }
} as const;
